### ISSUE TITLE
panicked at 'not yet implemented: method to load a Ref from the storage is not yet there'

### ISSUE THREAD

**Issue by isonis** [input-output-hk/shelley-testnet#114]
## Jormungandr occasionally stops with:

```
WARN error while streaming response: Error { code: Internal, cause: CannotIterate }, sub_task: server, task: network
thread 'block0' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr/src/blockchain/chain.rs:259:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
not yet implemented: method to load a Ref from the storage is not yet there
```

 ## Prerequisites information
1. `jcli --full-version`  jcli 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
1. `jormungandr --full-version`  jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
1. What is your Operating system? Ubuntu Server 18.04 LTS (running on Azure cloud)
1. What version of the jormungandr node are you using? 0.56
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)? No, downloaded and unzipped GNU binary release

## To Reproduce
1. Run: ./jormungandr --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --config node-config.yaml --secret node_secret.yaml
2. Cannot reproduce on demand. Occurs randomly

## Expected behavior
Crash free operation :-)

## Additional context
Now running with RUST_BACKTRACE=1 environment variable
Happened within ten minutes of me trying to sort out staking my account

````
##Waiting for new block to be created (timeout = 200 blocks = 400s)
New block was created - f34c5db41a85a0e929a83052d47720846668ede93f4cb49eaaec64482f16f081
 ##10. Check the account's delegation status
---
counter: 4
delegation:
  pools:
    - - f667ae183d5a1db8f408a563706f95538ee2fc49518a67b5fb12f2bac7c3c35b
      - 1
value: 9999955800

grebel@cardano-test:~/ada$ ./jcli rest v0 stake get -h http://127.0.0.1:3101/api | grep -A 1 c35b                                  
   - - f667ae183d5a1db8f408a563706f95538ee2fc49518a67b5fb12f2bac7c3c35b
      - 0
````

**Comment by isonis** [comment]
````
thread 'block0' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr/src/blockchain/chain.rs:259:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  10: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  11: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  12: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  13: jormungandr::blockchain::process::handle_input
  14: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  15: futures::task_impl::std::set
  16: tokio_threadpool::worker::Worker::run_task
  17: tokio_threadpool::worker::Worker::run
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  Oct 10 11:31:13.349 7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
    8: rust_begin_unwind
             at src/libstd/panicking.rs:311
WARN response canceled by the processing task, sub_task: server, task: network
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::option::expect_failed
             at src/libcore/option.rs:1166
  11: futures::future::chain::Chain<A,B,C>::poll
  12: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: tokio_threadpool::worker::Worker::run_task
  15: tokio_threadpool::worker::Worker::run
  16: std::thread::local::LocalKey<T>::with
  17: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Expect the event to not close
````

**Comment by isonis** [comment]
Only Fix I have is to delete contents of /tmp/jormungandr and start from scratch.
Rare failure estimated at one in 15 runs or less.

**Comment by isonis** [comment]
#### Crash with BACKTRACE=full
````
Oct 10 12:07:34.414 INFO PullBlocksToTip response stream failed: Error { code: Internal, source: Status { code: Internal, message: "internal processing error" } }, node_id: 15250992350008249921, peer_addr: 3.115.57.216:3000, task: network
thread 'block1' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr/src/blockchain/chain.rs:259:37
stack backtrace:
   0:     0x55f70a6905b8 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55f70a6905b8 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55f70a6905b8 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55f70a6905b8 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55f70a6905b8 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x55f70a68fd07 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x55f70a68fd07 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55f70a68f82f - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55f70a68f7dc - std::panicking::begin_panic_fmt::hc33ce01c7f7cd52d
                               at src/libstd/panicking.rs:339
   9:     0x55f70aa3c553 - <futures::future::either::Either<A,B> as futures::future::Future>::poll::h54ac36c9a967cdc6
  10:     0x55f70a82a994 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h7db5daee31ea9a87
  11:     0x55f70a82dd2d - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h8492a1fc553b9e29
  12:     0x55f70a839159 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::ha756c8f1f1936f9a
  13:     0x55f70a71b9e3 - jormungandr::blockchain::process::handle_input::ha32662c32f2f17e1
  14:     0x55f70a8e5bf3 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h1bb52cae7c745f31
  15:     0x55f70a685260 - futures::task_impl::std::set::hd9ec510cf0150311
  16:     0x55f70a681119 - tokio_threadpool::worker::Worker::run_task::hb0fbf803aefeedc9
  17:     0x55f70a67f450 - tokio_threadpool::worker::Worker::run::hfe33b62875b59f43
  18:     0x55f70a66651a - std::thread::local::LocalKey<T>::with::h5b446f6aa337e453
  19:     0x55f70a668de5 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h1b80f93eebd9ee0f
  20:     0x55f70a67d70f - std::sys_common::backtrace::__rust_begin_short_backtrace::h5265f18beb5741e8
  21:     0x55f70a67eb21 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbbbd61f19395b321
  22:     0x55f70a69e06f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  23:     0x55f70a69fb0c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  24:     0x55f70a69fb0c - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  25:     0x55f70a69fb0c - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  26:     0x7f6bbec976db - start_thread
  27:     0x7f6bbe7a888f - __clone
  28:                0x0 - <unknown>
not yet implemented: method to load a Ref from the storage is not yet there
thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
````

**Comment by carl-IOHK** [comment]
Hi @isonis thanks for the log info we have an open issue for this in https://github.com/input-output-hk/jormungandr/issues/788 but it's not resolved yet.

**Comment by isonis** [comment]
Thanks for pointing me in the right direction.  Perhaps the direction to check for previously reported issues should indicate that issues are logged in both the Shelley-testnet and the Jormungandr repositories.

I will check both in future.

**Comment by carl-IOHK** [comment]
No worries @isonis that's part of the reason we moved to the support portal so we can manage this better. In the support portal requesters may get informed of their issue while creating a request to they will be better informed and get help faster. 

Would you mind if we move this issue to the Support Portal? That way we can link it to the root casue issue and keep track of it better. To do that you could create a ticket here https://iohk.zendesk.com/hc/en-us/requests/new and drop note in this ticket with the ticket number. I would do it for you but I cannot since I do not have your email address.

**Comment by carl-IOHK** [comment]
Hi @isonis bump

**Comment by carl-IOHK** [comment]
@isonis We will close this request since we have not heard back assuming that your issue is resolved.
